#:schema node_modules/wrangler/config-schema.json
name = "sites-api"
main = "src/index.js"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]

[vars]
S3_BUCKET_URL = "https://nz-electricity-offers.s3.ap-southeast-2.amazonaws.com"
